require: 'rubocop-rspec'

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - config/initializers/devise.rb
    - vendor/**/*
    - cache/**/*
    - bundle/**/*
    - log/**/*
    - db/**/*
    - bin/*

inherit_from: .rubocop_todo.yml
