Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Metrics/MethodLength:
  Max: 20
Metrics/LineLength:
  Max: 120
Style/Lambda:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Style/MixinUsage:
  Enabled: false