language: ruby
rvm:
  - 2.5.1

services:
  - postgresql

before_script:
  - gem install bundler
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - npm install

script:
  - bundle exec rubocop --config .rubocop.yml
  - bundle exec rspec spec
  - bundle exec brakeman
  - yarn run lint
