development:
  adapter: postgresql
  database: work-list_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: work-list_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: work-list_production
  pool: 5
  timeout: 5000
